trainer: "SingleGameTrainer"
game: "ALE/Pong-v5"
device: "cuda:1"
episodes: 5000
render: false
debug: true
save_dir: "logs"
log_dir: "logs"

agents:
  CriticalA2C:
    agent_params:
      reg_strength: [0.0001, 0.001, 0.01]
    logics:
      A2CLogic:
        logic_params:
          gamma: [0.9, 0.99, 0.999]