trainer: "SingleGameTrainer"
game: "ALE/Pong-v5"
device: "cuda:0"
episodes: 5000
render: false
debug: true
save_dir: "logs"
log_dir: "logs"

agents:
  StandardAtariDQN:
    agent_params:
      epsilon: [0.0, 0.05, 0.1]
    logics:
      SARSALogic:
        logic_params:
          gamma: [0.9, 0.99, 0.999]