trainer: "SingleGameTrainer"
game: "ALE/Pong-v5"
device: "cuda:0"
episodes: 5000
render: false
debug: true
save_dir: "logs"
log_dir: "logs"

agents:
  PPOAgent:
    agent_params:
      epsilon: [0.0, 0.2]
    logics:
      PPOLogic:
        logic_params:
          gamma: [0.9, 0.99, 0.999]

  CriticalPPO:
    agent_params:
      epsilon: [0.0, 0.2]
      reg_strength: [0.0001, 0.001, 0.01]
    logics:
      PPOLogic:
        logic_params:
          gamma: [0.9, 0.99, 0.999]
