trainer: "SingleGameTrainer"
game: "ALE/Pong-v5"
device: "cuda"
episodes: 100
render: false
debug: true
save_dir: "logs"
log_dir: "logs"

agents:
  PongA2CAgent:
    logics:
      A2CLogic:
        logic_params:
          gamma: [0.9, 0.99, 0.999]

  PPOAgent:
    agent_params:
      epsilon: [0.0, 0.05, 0.1]
    logics:
      PPOLogic:
        logic_params:
          gamma: [0.9, 0.99, 0.999]

  StandardAtariDQN:
    agent_params:
      epsilon: [0.01, 0.05, 0.1]
    logics:
      TDLogic:
        logic_params:
          lr: [0.001, 0.01, 0.1]
          gamma: [0.9, 0.99, 0.999]
          batch_size: [1]
      SARSALogic:
        logic_params:
          lr: [0.001, 0.01, 0.1]
          gamma: [0.9, 0.99, 0.999]
          batch_size: [1]
      DiracRewardLogic:
        logic_params:
          rescale: [1, 10, 100]
          lr: [0.001, 0.01, 0.1]

  CriticalAgent:
    agent_params:
      reg_strength: [0.001, 0.01, 0.1]
    logics:
      TDLogic:
        logic_params:
          lr: [0.001, 0.01, 0.1]
          gamma: [0.9, 0.99, 0.999]
          batch_size: [1]
      SARSALogic:
        logic_params:
          lr: [0.001, 0.01, 0.1]
          gamma: [0.9, 0.99, 0.999]
          batch_size: [1]
      DiracRewardLogic:
        logic_params:
          rescale: [1, 10, 100]
          lr: [0.001, 0.01, 0.1]
          
  GatedAtariUDQN:
    agent_params:
      epsilon: [0.0, 0.05, 0.1]
    logics:
      TDLogic:
        logic_params:
          lr: [0.001, 0.01, 0.1]
          gamma: [0.9, 0.99, 0.999]
          batch_size: [1]
      SARSALogic:
        logic_params:
          lr: [0.001, 0.01, 0.1]
          gamma: [0.9, 0.99, 0.999]
          batch_size: [1]
      DiracRewardLogic:
        logic_params:
          rescale: [1, 10, 100]
          lr: [0.001, 0.01, 0.1]

  DynamicAtariUDQN:
    agent_params:
      epsilon: [0.0, 0.05, 0.1]
    logics:
      TDLogic:
        logic_params:
          lr: [0.001, 0.01, 0.1]
          gamma: [0.9, 0.99, 0.999]
          batch_size: [1]
      SARSALogic:
        logic_params:
          lr: [0.001, 0.01, 0.1]
          gamma: [0.9, 0.99, 0.999]
          batch_size: [1]
      DiracRewardLogic:
        logic_params:
          rescale: [1, 10, 100]
          lr: [0.001, 0.01, 0.1]

  GatedCriticalAtariUDQN:
    agent_params:
      epsilon: [0.0, 0.05, 0.1]
      reg_strength: [0.001, 0.01, 0.1]
    logics:
      TDLogic:
        logic_params:
          lr: [0.001, 0.01, 0.1]
          gamma: [0.9, 0.99, 0.999]
          batch_size: [1]
      SARSALogic:
        logic_params:
          lr: [0.001, 0.01, 0.1]
          gamma: [0.9, 0.99, 0.999]
          batch_size: [1]
      DiracRewardLogic:
        logic_params:
          rescale: [1, 10, 100]
          lr: [0.001, 0.01, 0.1]