trainer: "SingleGameTrainer"
game: "Pong-v5"
episodes: 2
render: false
debug: true
save_dir: "logs"
log_dir: "logs"
device: "cuda"  # Default device for training
parallel: true
max_jobs: 2  # Matches available GPUs

agents:
  PongA2CAgent:
    logics:
      A2CLogic:
        logic_params:
          gamma: [0.99]

  CriticalA2C:
    agent_params:
      reg_strength: [0.01]
    logics:
      A2CLogic:
        logic_params:
          gamma: [0.99]


  PPOAgent:
    agent_params:
      epsilon: [0.1]
    logics:
      PPOLogic:
        logic_params:
          gamma: [0.99]

  CriticalPPO:
    agent_params:
      epsilon: [0.1]
      reg_strength: [0.01]
    logics:
      PPOLogic:
        logic_params:
          gamma: [0.99]

  StandardAtariDQN:
    logics:
      TDLogic:
        logic_params:
          batch_size: [1]
      SARSALogic:
        logic_params:
          batch_size: [1]

  CriticalAgent:
    logics:
      TDLogic:
        logic_params:
          batch_size: [1]
      SARSALogic:
        logic_params:
          batch_size: [1]
          
  # GatedAtariUDQN:
  #   logics:
  #     TDLogic:
  #       logic_params:
  #         batch_size: [1]

  # DynamicAtariUDQN:
  #   logics:
  #     TDLogic:
  #       logic_params:
  #         batch_size: [1]

  # GatedCriticalAtariUDQN:
  #   logics:
  #     TDLogic:
  #       logic_params:
  #         batch_size: [1]
